const PLANETS=["Sun","Moon","Mars","Mercury","Jupiter","Venus","Saturn","Rahu","Ketu"];
const SYMBOLS={Sun:"Su",Moon:"Mo",Mars:"Ma",Mercury:"Me",Jupiter:"Ju",Venus:"Ve",Saturn:"Sa",Rahu:"Ra",Ketu:"Ke"};
const SOUTH=[["Pisces",0,0],["Aries",1,0],["Taurus",2,0],["Gemini",3,0],["Aquarius",0,1],["Cancer",3,1],["Capricorn",0,2],["Leo",3,2],["Sagittarius",0,3],["Scorpio",1,3],["Libra",2,3],["Virgo",3,3]];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const deg=v=>{const n=Number(v);if(!Number.isFinite(n))return"—";const d=Math.floor(n),m=Math.round((n-d)*60);return d+"° "+String(m).padStart(2,"0")+"′"};
const dateText=v=>{if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"})};
function planets(chart){const src=chart?.planets||{};return PLANETS.map(name=>{const p=src[name]||{};return{name,sign:p.zodiac_sign_name||p.sign||p.rashi||"—",degree:p.normDegree??p.degree??p.fullDegree,house:p.house_number??p.house??"—",nak:p.nakshatra_name||p.nakshatra||"—",pada:p.nakshatra_pada??p.pada??"—",retro:String(p.isRetro??"false").toLowerCase()==="true"}})}
function period(p){if(!p)return"—";return(p.lord||p.name||"—")+(p.start||p.end?" • "+dateText(p.start)+" – "+dateText(p.end):"")}
function chartHtml(chart){const ps=planets(chart),a=chart?.ascendant||{},asc=a.zodiac_sign_name||a.sign||"—",by={};ps.forEach(p=>(by[p.sign]??=[]).push(p));return'<div class="kundali-chart">'+SOUTH.map(([s,c,r])=>'<div class="chart-cell" style="grid-column:'+(c+1)+';grid-row:'+(r+1)+'"><span class="chart-sign">'+s+'</span>'+(asc===s?'<span class="chart-lagna">Lagna</span>':"")+'<div class="chart-planets">'+(by[s]||[]).map(p=>'<span>'+SYMBOLS[p.name]+(p.retro?"℞":"")+'</span>').join("")+'</div></div>').join("")+'<div class="chart-center"><strong>D1</strong><span>Rasi</span></div></div><p class="chart-note">Su Sun • Mo Moon • Ma Mars • Me Mercury • Ju Jupiter • Ve Venus • Sa Saturn • Ra Rahu • Ke Ketu</p>'}
function render(data){const c=data.chart||{},ps=planets(c),a=c.ascendant||{},asc=a.zodiac_sign_name||"—",moon=ps.find(p=>p.name==="Moon"),maha=data.dasha?.mahadasha,antar=data.dasha?.antardasha;document.getElementById("resultsContainer").innerHTML='<div class="section-head"><div><h2>Janma Kundali</h2><p>Lahiri sidereal • Whole-sign houses</p></div><span class="api-badge">Calculated</span></div><div class="kundali-top-grid"><div class="tile"><div class="tile-label">Lagna</div><div class="tile-value">'+esc(asc)+'</div><small>'+deg(a.fullDegree??a.normDegree)+'</small></div><div class="tile"><div class="tile-label">Moon Rashi</div><div class="tile-value">'+esc(moon?.sign)+'</div><small>'+esc(moon?.nak)+'</small></div><div class="tile"><div class="tile-label">Nakshatra Pada</div><div class="tile-value">'+esc(moon?.nak)+'</div><small>Pada '+esc(moon?.pada)+'</small></div></div><div class="chart-wrap"><div class="section-head"><div><h3>Rasi Chart (D1)</h3><p>South Indian style</p></div></div>'+chartHtml(c)+'</div><div class="section-head"><div><h3>Planetary Positions</h3><p>Sign, degree, house and Nakshatra</p></div></div><div class="table-scroll"><table class="kundali-table"><thead><tr><th>Planet</th><th>Sign</th><th>Degree</th><th>House</th><th>Nakshatra</th><th>Status</th></tr></thead><tbody>'+ps.map(p=>'<tr><td><strong>'+SYMBOLS[p.name]+'</strong> '+p.name+'</td><td>'+esc(p.sign)+'</td><td>'+deg(p.degree)+'</td><td>'+esc(p.house)+'</td><td>'+esc(p.nak)+' ('+esc(p.pada)+')</td><td>'+(p.retro?"Retrograde":"Direct")+'</td></tr>').join("")+'</tbody></table></div><div class="dasha-grid"><div class="dasha-card active"><div class="tile-label">Current Mahadasha</div><strong>'+esc(maha?.lord||"—")+'</strong><span>'+esc(period(maha))+'</span></div><div class="dasha-card"><div class="tile-label">Current Antardasha</div><strong>'+esc(antar?.lord||"—")+'</strong><span>'+esc(period(antar))+'</span></div></div><div class="calculation-note"><strong>Calculation:</strong> Navamsha • Lahiri ayanamsha • Whole-sign houses • precise birth coordinates for Lagna.</div><div class="actions pdf-actions"><button class="btn btn-primary" id="downloadPdfBtn">Download Kundali PDF</button></div>';document.getElementById("downloadPdfBtn").onclick=()=>downloadPdf(data)}
async function generateKundali(){const date=document.getElementById("birthDate").value,time=document.getElementById("birthTime").value,city=document.getElementById("birthCity").value.trim()||"Hyderabad",box=document.getElementById("resultsContainer"),btn=document.getElementById("calculateBtn");if(!date||!time){box.innerHTML='<div class="message error">Please enter both birth date and birth time.</div>';return}btn.disabled=true;btn.textContent="Calculating…";box.innerHTML='<div class="loading-card"><div class="spinner"></div><strong>Calculating your Vedic chart…</strong><span>Fetching accurate Lagna, planets and Vimshottari Dasha.</span></div>';try{const r=await fetch("/.netlify/functions/kundali",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({birthDate:date,birthTime:time,birthCity:city})}),data=await r.json();if(!r.ok||!data.ok)throw new Error(data.error||"Unable to generate Kundali.");render(data);box.scrollIntoView({behavior:"smooth",block:"start"})}catch(e){box.innerHTML='<div class="message error"><strong>Could not generate Kundali.</strong><br>'+esc(e.message)+'</div>'}finally{btn.disabled=false;btn.textContent="Generate Kundali"}}
window.SiddhaKundali={generateKundali};
document.addEventListener("DOMContentLoaded",()=>document.getElementById("calculateBtn")?.addEventListener("click",generateKundali));
async function logoData(){const r=await fetch("/logo.png"),b=await r.blob();return await new Promise((res,rej)=>{const f=new FileReader();f.onload=()=>res(f.result);f.onerror=rej;f.readAsDataURL(b)})}
function pdfChart(doc,chart,x,y,size){const cell=size/4,by={};planets(chart).forEach(p=>(by[p.sign]??=[]).push(p));doc.setDrawColor(79,117,103);doc.setLineWidth(.5);doc.rect(x,y,size,size);[1,2,3].forEach(i=>{doc.line(x+i*cell,y,x+i*cell,y+size);doc.line(x,y+i*cell,x+size,y+i*cell)});SOUTH.forEach(([s,c,r])=>{const cx=x+c*cell,cy=y+r*cell;doc.setFontSize(6);doc.setFont("helvetica","bold");doc.text(s,cx+2,cy+7);(by[s]||[]).forEach((p,i)=>doc.text(SYMBOLS[p.name]+(p.retro?" R":""),cx+2,cy+16+i*7))});doc.setFontSize(8);doc.text("D1 Rasi",x+size/2,y+size/2,{align:"center"})}
async function downloadPdf(data){
 if(!window.jspdf?.jsPDF){alert("PDF generator is still loading. Please try again.");return}
 const{jsPDF}=window.jspdf,doc=new jsPDF({unit:"mm",format:"a4"}),m=15,W=210,H=297;
 const disclaimer="Astrology consultations, mantras, spiritual remedies, rituals, prayers, and related services do not guarantee any specific results. Outcomes and experiences vary from person to person and depend on individual circumstances. By using these services, you acknowledge that results are uncertain and cannot be assured.";
 const footer=()=>{doc.setDrawColor(223,231,225);doc.line(m,H-23,W-m,H-23);doc.setFont("helvetica","normal");doc.setFontSize(6);doc.setTextColor(105,118,111);doc.text(doc.splitTextToSize(disclaimer,W-m*2),m,H-19,{lineHeightFactor:1.15});doc.text("Siddha Astro • Page "+doc.getNumberOfPages(),m,H-7);doc.text("Vedic chart report",W-m,H-7,{align:"right"})};
 footer();
 try{const r=await fetch("/logo.png"),b=await r.blob(),d=await new Promise((res,rej)=>{const f=new FileReader();f.onload=()=>res(f.result);f.onerror=rej;f.readAsDataURL(b)});doc.addImage(d,"PNG",m,11,18,18)}catch{}
 const b=data.birth,c=data.chart||{},ps=planets(c),a=c.ascendant||{},moon=ps.find(p=>p.name==="Moon");
 doc.setTextColor(38,51,47);doc.setFont("helvetica","bold");doc.setFontSize(19);doc.text("Siddha Astro",38,20);doc.setFontSize(9);doc.setFont("helvetica","normal");doc.setTextColor(104,118,111);doc.text("Vedic Birth Chart • Janma Kundali",38,27);
 doc.setTextColor(38,51,47);doc.setFont("helvetica","bold");doc.setFontSize(11);doc.text("Birth Details",m,45);doc.setFont("helvetica","normal");doc.setFontSize(9);doc.text("Date: "+b.date,m,53);doc.text("Time: "+b.time,m,60);doc.text("Place: "+b.city,m,67);doc.text("Coordinates: "+Number(b.latitude).toFixed(4)+", "+Number(b.longitude).toFixed(4),m,74);
 doc.setFillColor(229,239,233);doc.roundedRect(112,43,83,36,4,4,"F");doc.setTextColor(54,89,77);doc.setFont("helvetica","bold");doc.setFontSize(8);doc.text("LAGNA",118,51);doc.setFontSize(13);doc.text(a.zodiac_sign_name||"—",118,59);doc.setFontSize(8);doc.text("Moon: "+(moon?.sign||"—"),118,67);doc.text("Nakshatra: "+(moon?.nak||"—"),118,73);
 doc.setTextColor(38,51,47);doc.setFontSize(11);doc.text("Rasi Chart (D1)",m,89);pdfChart(doc,c,m,95,110);
 doc.setFont("helvetica","bold");doc.text("Current Vimshottari Dasha",m,217);doc.setFont("helvetica","normal");doc.setFontSize(9);doc.text("Mahadasha: "+(data.dasha?.mahadasha?.lord||"—")+" • "+period(data.dasha?.mahadasha),m,225);doc.text("Antardasha: "+(data.dasha?.antardasha?.lord||"—")+" • "+period(data.dasha?.antardasha),m,232);
 doc.setFont("helvetica","bold");doc.setFontSize(11);doc.text("Planetary Positions",m,244);let y=251;doc.setFontSize(7);doc.text("Planet",m,y);doc.text("Sign",42,y);doc.text("Degree",80,y);doc.text("House",113,y);doc.text("Nakshatra",138,y);doc.setFont("helvetica","normal");y+=6;
 ps.forEach(p=>{doc.text(p.name,m,y);doc.text(String(p.sign).slice(0,14),42,y);doc.text(deg(p.degree),80,y);doc.text(String(p.house),113,y);doc.text(String(p.nak).slice(0,18),138,y);y+=6});
 doc.save("Siddha-Astro-Kundali-"+b.date+".pdf");
}
window.SiddhaKundali.downloadPdf=downloadPdf;
