const PLANETS=["Sun","Moon","Mars","Mercury","Jupiter","Venus","Saturn","Rahu","Ketu"];
const SYMBOLS={Sun:"Su",Moon:"Mo",Mars:"Ma",Mercury:"Me",Jupiter:"Ju",Venus:"Ve",Saturn:"Sa",Rahu:"Ra",Ketu:"Ke"};
const SOUTH=[["Pisces",0,0],["Aries",1,0],["Taurus",2,0],["Gemini",3,0],["Aquarius",0,1],["Cancer",3,1],["Capricorn",0,2],["Leo",3,2],["Sagittarius",0,3],["Scorpio",1,3],["Libra",2,3],["Virgo",3,3]];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const deg=v=>{const n=Number(v);if(!Number.isFinite(n))return"—";const d=Math.floor(n),m=Math.round((n-d)*60);return d+"° "+String(m).padStart(2,"0")+"′"};
const dateText=v=>{if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"})};
function planets(chart){const src=chart?.planets||{};return PLANETS.map(name=>{const p=src[name]||{};return{name,sign:p.zodiac_sign_name||p.sign||p.rashi||"—",degree:p.normDegree??p.degree??p.fullDegree,house:p.house_number??p.house??"—",nak:p.nakshatra_name||p.nakshatra||"—",pada:p.nakshatra_pada??p.pada??"—",retro:String(p.isRetro??"false").toLowerCase()==="true"}})}
function period(p){if(!p)return"—";return(p.lord||p.name||"—")+(p.start||p.end?" • "+dateText(p.start)+" – "+dateText(p.end):"")}
function chartHtml(chart){const ps=planets(chart),a=chart?.ascendant||{},asc=a.zodiac_sign_name||a.sign||"—",by={};ps.forEach(p=>(by[p.sign]??=[]).push(p));return'<div class="kundali-chart">'+SOUTH.map(([s,c,r])=>'<div class="chart-cell" style="grid-column:'+(c+1)+';grid-row:'+(r+1)+'"><span class="chart-sign">'+s+'</span>'+(asc===s?'<span class="chart-lagna">Lagna</span>':"")+'<div class="chart-planets">'+(by[s]||[]).map(p=>'<span>'+SYMBOLS[p.name]+(p.retro?"℞":"")+'</span>').join("")+'</div></div>').join("")+'<div class="chart-center"><strong>D1</strong><span>Rasi</span></div></div><p class="chart-note">Su Sun • Mo Moon • Ma Mars • Me Mercury • Ju Jupiter • Ve Venus • Sa Saturn • Ra Rahu • Ke Ketu</p>'}
function render(data){const c=data.chart||{},ps=planets(c),a=c.ascendant||{},asc=a.zodiac_sign_name||"—",moon=ps.find(p=>p.name==="Moon"),maha=data.dasha?.mahadasha,antar=data.dasha?.antardasha;document.getElementById("resultsContainer").innerHTML='<div class="section-head"><div><h2>Janma Kundali</h2><p>Lahiri sidereal • Whole-sign houses</p></div><span class="api-badge">Calculated</span></div><div class="kundali-top-grid"><div class="tile"><div class="tile-label">Lagna</div><div class="tile-value">'+esc(asc)+'</div><small>'+deg(a.fullDegree??a.normDegree)+'</small></div><div class="tile"><div class="tile-label">Moon Rashi</div><div class="tile-value">'+esc(moon?.sign)+'</div><small>'+esc(moon?.nak)+'</small></div><div class="tile"><div class="tile-label">Nakshatra Pada</div><div class="tile-value">'+esc(moon?.nak)+'</div><small>Pada '+esc(moon?.pada)+'</small></div></div><div class="chart-wrap"><div class="section-head"><div><h3>Rasi Chart (D1)</h3><p>South Indian style</p></div></div>'+chartHtml(c)+'</div><div class="section-head"><div><h3>Planetary Positions</h3><p>Sign, degree, house and Nakshatra</p></div></div><div class="table-scroll"><table class="kundali-table"><thead><tr><th>Planet</th><th>Sign</th><th>Degree</th><th>House</th><th>Nakshatra</th><th>Status</th></tr></thead><tbody>'+ps.map(p=>'<tr><td><strong>'+SYMBOLS[p.name]+'</strong> '+p.name+'</td><td>'+esc(p.sign)+'</td><td>'+deg(p.degree)+'</td><td>'+esc(p.house)+'</td><td>'+esc(p.nak)+' ('+esc(p.pada)+')</td><td>'+(p.retro?"Retrograde":"Direct")+'</td></tr>').join("")+'</tbody></table></div><div class="dasha-grid"><div class="dasha-card active"><div class="tile-label">Current Mahadasha</div><strong>'+esc(maha?.lord||"—")+'</strong><span>'+esc(period(maha))+'</span></div><div class="dasha-card"><div class="tile-label">Current Antardasha</div><strong>'+esc(antar?.lord||"—")+'</strong><span>'+esc(period(antar))+'</span></div></div><div class="calculation-note"><strong>Calculation:</strong> Navamsha • Lahiri ayanamsha • Whole-sign houses • precise birth coordinates for Lagna.</div><div class="actions pdf-actions"><button class="btn btn-primary" id="downloadPdfBtn">Download Kundali PDF</button></div>';document.getElementById("downloadPdfBtn").onclick=()=>downloadPdf(data)}
async function generateKundali(){const date=document.getElementById("birthDate").value,time=document.getElementById("birthTime").value,city=document.getElementById("birthCity").value.trim()||"Hyderabad",box=document.getElementById("resultsContainer"),btn=document.getElementById("calculateBtn");if(!date||!time){box.innerHTML='<div class="message error">Please enter both birth date and birth time.</div>';return}btn.disabled=true;btn.textContent="Calculating…";box.innerHTML='<div class="loading-card"><div class="spinner"></div><strong>Calculating your Vedic chart…</strong><span>Fetching accurate Lagna, planets and Vimshottari Dasha.</span></div>';try{const r=await fetch("/.netlify/functions/kundali",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({birthDate:date,birthTime:time,birthCity:city})}),data=await r.json();if(!r.ok||!data.ok)throw new Error(data.error||"Unable to generate Kundali.");render(data);box.scrollIntoView({behavior:"smooth",block:"start"})}catch(e){box.innerHTML='<div class="message error"><strong>Could not generate Kundali.</strong><br>'+esc(e.message)+'</div>'}finally{btn.disabled=false;btn.textContent="Generate Kundali"}}
window.SiddhaKundali={generateKundali};
document.addEventListener("DOMContentLoaded",()=>document.getElementById("calculateBtn")?.addEventListener("click",generateKundali));