const PLANETS=["Sun","Moon","Mars","Mercury","Jupiter","Venus","Saturn","Rahu","Ketu"];
const SYMBOLS={Sun:"Su",Moon:"Mo",Mars:"Ma",Mercury:"Me",Jupiter:"Ju",Venus:"Ve",Saturn:"Sa",Rahu:"Ra",Ketu:"Ke"};
const SOUTH=[["Pisces",0,0],["Aries",1,0],["Taurus",2,0],["Gemini",3,0],["Aquarius",0,1],["Cancer",3,1],["Capricorn",0,2],["Leo",3,2],["Sagittarius",0,3],["Scorpio",1,3],["Libra",2,3],["Virgo",3,3]];
const TE={Sun:"సూర్యుడు",Moon:"చంద్రుడు",Mars:"కుజుడు",Mercury:"బుధుడు",Jupiter:"గురుడు",Venus:"శుక్రుడు",Saturn:"శని",Rahu:"రాహు",Ketu:"కేతు",Pisces:"మీనం",Aries:"మేషం",Taurus:"వృషభం",Gemini:"మిథునం",Aquarius:"కుంభం",Cancer:"కర్కాటకం",Capricorn:"మకరం",Leo:"సింహం",Sagittarius:"ధనుస్సు",Scorpio:"వృశ్చికం",Libra:"తుల",Virgo:"కన్య",Lagna:"లగ్నం",Rasi:"రాశి",Retrograde:"వక్రగతి",Direct:"మార్గి"};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const NAK_TE={"Ashwini":"అశ్విని","Bharani":"భరణి","Krittika":"కృత్తిక","Rohini":"రోహిణి","Mrigashira":"మృగశిర","Ardra":"ఆర్ద్ర","Punarvasu":"పునర్వసు","Pushya":"పుష్యమి","Ashlesha":"ఆశ్లేష","Magha":"మఘ","Purva Phalguni":"పూర్వ ఫల్గుణి","Uttara Phalguni":"ఉత్తర ఫల్గుణి","Hasta":"హస్త","Chitra":"చిత్త","Swati":"స్వాతి","Vishakha":"విశాఖ","Anuradha":"అనూరాధ","Jyeshtha":"జ్యేష్ఠ","Mula":"మూల","Purva Ashadha":"పూర్వాషాఢ","Uttara Ashadha":"ఉత్తరాషాఢ","Shravana":"శ్రవణం","Dhanishtha":"ధనిష్ఠ","Shatabhisha":"శతభిషం","Purva Bhadrapada":"పూర్వాభాద్ర","Uttara Bhadrapada":"ఉత్తరాభాద్ర","Revati":"రేవతి"};const tr=v=>SiddhaApp.getLanguage()==="te"?(TE[v]||v):v;const trNak=v=>SiddhaApp.getLanguage()==="te"?(NAK_TE[v]||v):v;
const deg=v=>{const n=Number(v);if(!Number.isFinite(n))return"—";const d=Math.floor(n),m=Math.round((n-d)*60);return d+"° "+String(m).padStart(2,"0")+"′"};
const dateText=v=>{if(!v)return"—";const d=new Date(v);if(Number.isNaN(d.getTime()))return v;return d.toLocaleDateString(SiddhaApp.getLanguage()==="te"?"te-IN":"en-IN",{day:"2-digit",month:"short",year:"numeric"})};
function planets(chart){const src=chart?.planets||{};return PLANETS.map(name=>{const p=src[name]||{};return{name,sign:p.zodiac_sign_name||p.sign||p.rashi||"—",degree:p.normDegree??p.degree??p.fullDegree,house:p.house_number??p.house??"—",nak:p.nakshatra_name||p.nakshatra||"—",pada:p.nakshatra_pada??p.pada??"—",retro:String(p.isRetro??"false").toLowerCase()==="true"}})}
function period(p){if(!p)return"—";return(p.lord||p.name||"—")+(p.start||p.end?" • "+dateText(p.start)+" – "+dateText(p.end):"")}
function chartHtml(chart){const ps=planets(chart),a=chart?.ascendant||{},asc=a.zodiac_sign_name||a.sign||"—",by={};ps.forEach(p=>(by[p.sign]??=[]).push(p));return'<div class="kundali-chart">'+SOUTH.map(([s,c,r])=>'<div class="chart-cell" style="grid-column:'+(c+1)+';grid-row:'+(r+1)+'"><span class="chart-sign">'+tr(s)+'</span>'+(asc===s?'<span class="chart-lagna">'+tr("Lagna")+'</span>':"")+'<div class="chart-planets">'+(by[s]||[]).map(p=>'<span>'+SYMBOLS[p.name]+(p.retro?"℞":"")+'</span>').join("")+'</div></div>').join("")+'<div class="chart-center"><strong>D1</strong><span>'+tr("Rasi")+'</span></div></div><p class="chart-note">Su '+tr("Sun")+' • Mo '+tr("Moon")+' • Ma '+tr("Mars")+' • Me '+tr("Mercury")+' • Ju '+tr("Jupiter")+' • Ve '+tr("Venus")+' • Sa '+tr("Saturn")+' • Ra '+tr("Rahu")+' • Ke '+tr("Ketu")+'</p>'}
function render(data){const c=data.chart||{},ps=planets(c),a=c.ascendant||{},asc=a.zodiac_sign_name||"—",moon=ps.find(p=>p.name==="Moon"),maha=data.dasha?.mahadasha,antar=data.dasha?.antardasha,te=SiddhaApp.getLanguage()==="te";document.getElementById("resultsContainer").innerHTML='<div class="section-head"><div><h2>'+tr("Janma Kundali")+'</h2><p>'+ (te?"లాహిరి సైడీరియల్ • సంపూర్ణ రాశి గృహాలు":"Lahiri sidereal • Whole-sign houses")+'</p></div><span class="api-badge">'+(te?"లెక్కించబడింది":"Calculated")+'</span></div><div class="kundali-top-grid"><div class="tile"><div class="tile-label">'+tr("Lagna")+'</div><div class="tile-value">'+esc(tr(asc))+'</div><small>'+deg(a.fullDegree??a.normDegree)+'</small></div><div class="tile"><div class="tile-label">'+tr("Moon Rashi")+'</div><div class="tile-value">'+esc(tr(moon?.sign))+'</div><small>'+esc(trNak(moon?.nak))+'</small></div><div class="tile"><div class="tile-label">'+tr("Nakshatra Pada")+'</div><div class="tile-value">'+esc(moon?.nak)+'</div><small>'+ (te?"పాదం ":"Pada ")+esc(moon?.pada)+'</small></div></div><div class="chart-wrap"><div class="section-head"><div><h3>'+ (te?"రాశి చార్ట్ (D1)":"Rasi Chart (D1)")+'</h3><p>'+ (te?"దక్షిణ భారత శైలి":"South Indian style")+'</p></div></div>'+chartHtml(c)+'</div><div class="section-head"><div><h3>'+ (te?"గ్రహ స్థితులు":"Planetary Positions")+'</h3><p>'+ (te?"రాశి, డిగ్రీ, భావం మరియు నక్షత్రం":"Sign, degree, house and Nakshatra")+'</p></div></div><div class="table-scroll"><table class="kundali-table"><thead><tr><th>'+ (te?"గ్రహం":"Planet")+'</th><th>'+ (te?"రాశి":"Sign")+'</th><th>'+ (te?"డిగ్రీ":"Degree")+'</th><th>'+ (te?"భావం":"House")+'</th><th>'+ (te?"నక్షత్రం":"Nakshatra")+'</th><th>'+ (te?"స్థితి":"Status")+'</th></tr></thead><tbody>'+ps.map(p=>'<tr><td><strong>'+SYMBOLS[p.name]+'</strong> '+tr(p.name)+'</td><td>'+esc(tr(p.sign))+'</td><td>'+deg(p.degree)+'</td><td>'+esc(p.house)+'</td><td>'+esc(trNak(p.nak))+' ('+esc(p.pada)+')</td><td>'+tr(p.retro?"Retrograde":"Direct")+'</td></tr>').join("")+'</tbody></table></div><div class="dasha-grid"><div class="dasha-card active"><div class="tile-label">'+(te?"ప్రస్తుత మహాదశ":"Current Mahadasha")+'</div><strong>'+esc(tr(maha?.lord||"—"))+'</strong><span>'+esc(period(maha))+'</span></div><div class="dasha-card"><div class="tile-label">'+(te?"ప్రస్తుత అంతర్దశ":"Current Antardasha")+'</div><strong>'+esc(tr(antar?.lord||"—"))+'</strong><span>'+esc(period(antar))+'</span></div></div><div class="calculation-note"><strong>'+ (te?"లెక్కింపు:":"Calculation:")+'</strong> Navamsha • Lahiri ayanamsha • Whole-sign houses • '+(te?"లగ్నం కోసం ఖచ్చితమైన జన్మ స్థల కోఆర్డినేట్లు.":"precise birth coordinates for Lagna.")+'</div><div class="actions pdf-actions"><button class="btn btn-primary" id="downloadPdfBtn">'+(te?"కుండలి PDF డౌన్‌లోడ్ చేయండి":"Download Kundali PDF")+'</button></div>';document.getElementById("downloadPdfBtn").onclick=()=>downloadPdf(data)}
async function generateKundali(){const name=document.getElementById("birthName").value.trim(),date=document.getElementById("birthDate").value,time=document.getElementById("birthTime").value,city=document.getElementById("birthCity").value.trim()||"Hyderabad",latitude=Number(document.getElementById("birthLatitude")?.value),longitude=Number(document.getElementById("birthLongitude")?.value),timezoneName=document.getElementById("birthTimezone")?.value||"Asia/Kolkata",country=document.getElementById("birthCountry")?.value||"",box=document.getElementById("resultsContainer"),btn=document.getElementById("calculateBtn"),te=SiddhaApp.getLanguage()==="te";if(!Number.isFinite(latitude)||!Number.isFinite(longitude)||!timezoneName){box.innerHTML='<div class="message error">'+(te?"దయచేసి మీ జన్మస్థలాన్ని శోధన ఫలితాల నుండి ఎంచుకోండి.":"Please select your birth place from the worldwide search results.")+"</div>";return}if(!date||!time){box.innerHTML='<div class="message error">'+(te?"దయచేసి జన్మ తేదీ మరియు సమయాన్ని నమోదు చేయండి.":"Please enter both birth date and birth time.")+'</div>';return}btn.disabled=true;btn.textContent=te?"లెక్కిస్తోంది…":"Calculating…";box.innerHTML='<div class="loading-card"><div class="spinner"></div><strong>'+ (te?"మీ వేద కుండలిని లెక్కిస్తోంది…":"Calculating your Vedic chart…")+'</strong><span>'+ (te?"ఖచ్చితమైన లగ్నం, గ్రహాలు మరియు విమ్షోత్తరి దశను పొందుతోంది.":"Fetching accurate Lagna, planets and Vimshottari Dasha.")+'</span></div>';try{const r=await fetch("/.netlify/functions/kundali",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,birthDate:date,birthTime:time,birthCity:city,latitude,longitude,timezoneName,country})}),data=await r.json();if(!r.ok||!data.ok)throw new Error(data.error||"Unable to generate Kundali.");window.SiddhaKundali.lastData=data;render(data);box.scrollIntoView({behavior:"smooth",block:"start"})}catch(e){box.innerHTML='<div class="message error"><strong>'+ (te?"కుండలి రూపొందించలేకపోయాము.":"Could not generate Kundali.")+'</strong><br>'+esc(e.message)+'</div>'}finally{btn.disabled=false;btn.textContent=te?"కుండలి రూపొందించండి":"Generate Kundali"}}
window.SiddhaKundali={generateKundali};
document.addEventListener("DOMContentLoaded",()=>document.getElementById("calculateBtn")?.addEventListener("click",generateKundali));document.addEventListener("DOMContentLoaded",()=>{const input=document.getElementById("birthPlaceSearch"),list=document.getElementById("placeSuggestions"),status=document.getElementById("placeStatus"),city=document.getElementById("birthCity"),lat=document.getElementById("birthLatitude"),lon=document.getElementById("birthLongitude"),tz=document.getElementById("birthTimezone"),country=document.getElementById("birthCountry");if(!input||!list)return;let timer=null,controller=null;const setStatus=t=>{status.textContent="📍 "+t};const close=()=>{list.classList.remove("open");list.innerHTML=""};const selectPlace=p=>{const label=[p.name,p.admin1,p.country].filter(Boolean).join(", ");input.value=label;city.value=p.name||"";lat.value=Number(p.latitude).toFixed(6);lon.value=Number(p.longitude).toFixed(6);tz.value=p.timezone||"UTC";country.value=p.country||"";setStatus(label);close()};const search=async()=>{const q=input.value.trim();if(q.length<2){close();return}if(controller)controller.abort();controller=new AbortController();list.innerHTML='<div class="place-searching">Searching worldwide…</div>';list.classList.add("open");try{const url="https://geocoding-api.open-meteo.com/v1/search?name="+encodeURIComponent(q)+"&count=6&language=en&format=json";const r=await fetch(url,{signal:controller.signal});if(!r.ok)throw new Error("Location search unavailable");const data=await r.json();const results=(data.results||[]).filter(x=>Number.isFinite(Number(x.latitude))&&Number.isFinite(Number(x.longitude)));if(!results.length){list.innerHTML='<div class="place-empty">No matching place found. Try the city or nearest town name.</div>';return}list.innerHTML=results.map((p,i)=>'<button type="button" class="place-option" data-place-index="'+i+'"><strong>'+esc(p.name||"Unknown place")+'</strong><span>'+esc([p.admin1,p.country].filter(Boolean).join(", "))+(p.timezone?" • "+esc(p.timezone):"")+'</span></button>').join("");list.querySelectorAll("[data-place-index]").forEach((b,i)=>b.addEventListener("click",()=>selectPlace(results[i])))}catch(e){if(e.name==="AbortError")return;list.innerHTML='<div class="place-empty">Unable to search right now. Please try again.</div>'}};input.addEventListener("input",()=>{city.value="";lat.value="";lon.value="";tz.value="";country.value="";status.textContent="Select a location from the search results";clearTimeout(timer);timer=setTimeout(search,350)});input.addEventListener("focus",()=>{if(input.value.trim().length>=2)search()});input.addEventListener("keydown",e=>{if(e.key==="Escape")close()});document.addEventListener("click",e=>{if(!e.target.closest(".birth-place-wrap"))close()})})();
document.addEventListener("languagechange",()=>{const box=document.getElementById("resultsContainer");if(window.SiddhaKundali?.lastData)render(window.SiddhaKundali.lastData)});
async function logoData(){const r=await fetch("/logo.png"),b=await r.blob();return await new Promise((res,rej)=>{const f=new FileReader();f.onload=()=>res(f.result);f.onerror=rej;f.readAsDataURL(b)})}
function pdfChart(doc,chart,x,y,size){const cell=size/4,by={};planets(chart).forEach(p=>(by[p.sign]??=[]).push(p));doc.setDrawColor(79,117,103);doc.setLineWidth(.5);doc.rect(x,y,size,size);[1,2,3].forEach(i=>{doc.line(x+i*cell,y,x+i*cell,y+size);doc.line(x,y+i*cell,x+size,y+i*cell)});SOUTH.forEach(([s,c,r])=>{const cx=x+c*cell,cy=y+r*cell;doc.setFontSize(6);doc.setFont("helvetica","bold");doc.text(tr(s),cx+2,cy+7);(by[s]||[]).forEach((p,i)=>doc.text(SYMBOLS[p.name]+(p.retro?" R":""),cx+2,cy+16+i*7))});doc.setFontSize(8);doc.text("D1 "+tr("Rasi"),x+size/2,y+size/2,{align:"center"})}
async function downloadPdf(data){
 if(!window.jspdf?.jsPDF){alert(SiddhaApp.getLanguage()==="te"?"PDF జనరేటర్ ఇంకా లోడ్ అవుతోంది. దయచేసి మళ్లీ ప్రయత్నించండి.":"PDF generator is still loading. Please try again.");return}
 const{jsPDF}=window.jspdf,doc=new jsPDF({unit:"mm",format:"a4"}),m=15,W=210,H=297;
 const disclaimer="Astrology consultations, mantras, spiritual remedies, rituals, prayers, and related services do not guarantee any specific results. Outcomes and experiences vary from person to person and depend on individual circumstances. By using these services, you acknowledge that results are uncertain and cannot be assured.";
 const footer=()=>{doc.setDrawColor(223,231,225);doc.line(m,H-23,W-m,H-23);doc.setFont("helvetica","normal");doc.setFontSize(6);doc.setTextColor(105,118,111);doc.text(doc.splitTextToSize(disclaimer,W-m*2),m,H-19,{lineHeightFactor:1.15});doc.text("Siddha Astro • Page "+doc.getNumberOfPages(),m,H-7);doc.text("Vedic chart report",W-m,H-7,{align:"right"})};
 footer();
 try{const r=await fetch("/logo.png"),b=await r.blob(),d=await new Promise((res,rej)=>{const f=new FileReader();f.onload=()=>res(f.result);f.onerror=rej;f.readAsDataURL(b)});doc.addImage(d,"PNG",m,11,18,18)}catch{}
 const b=data.birth,c=data.chart||{},ps=planets(c),a=c.ascendant||{},moon=ps.find(p=>p.name==="Moon");
 doc.setTextColor(38,51,47);doc.setFont("helvetica","bold");doc.setFontSize(19);doc.text("Siddha Astro",38,20);doc.setFontSize(9);doc.setFont("helvetica","normal");doc.setTextColor(104,118,111);doc.text(SiddhaApp.getLanguage()==="te"?"వేద జన్మ చార్ట్ • జన్మ కుండలి":"Vedic Birth Chart • Janma Kundali",38,27);
 doc.setTextColor(38,51,47);doc.setFont("helvetica","bold");doc.setFontSize(11);doc.text(SiddhaApp.getLanguage()==="te"?"జన్మ వివరాలు":"Birth Details",m,45);doc.setFont("helvetica","normal");doc.setFontSize(9);doc.text((SiddhaApp.getLanguage()==="te"?"తేదీ: ":"Date: ")+b.date,m,53);doc.text((SiddhaApp.getLanguage()==="te"?"సమయం: ":"Time: ")+b.time,m,60);doc.text((SiddhaApp.getLanguage()==="te"?"స్థలం: ":"Place: ")+b.city,m,67);doc.text((SiddhaApp.getLanguage()==="te"?"కోఆర్డినేట్లు: ":"Coordinates: ")+Number(b.latitude).toFixed(4)+", "+Number(b.longitude).toFixed(4),m,74);
 doc.setFillColor(229,239,233);doc.roundedRect(112,43,83,36,4,4,"F");doc.setTextColor(54,89,77);doc.setFont("helvetica","bold");doc.setFontSize(8);doc.text(SiddhaApp.getLanguage()==="te"?"లగ్నం":"LAGNA",118,51);doc.setFontSize(13);doc.text(tr(a.zodiac_sign_name||"—"),118,59);doc.setFontSize(8);doc.text((SiddhaApp.getLanguage()==="te"?"చంద్రుడు: ":"Moon: ")+tr(moon?.sign||"—"),118,67);doc.text((SiddhaApp.getLanguage()==="te"?"నక్షత్రం: ":"Nakshatra: ")+(trNak(moon?.nak)||"—"),118,73);
 doc.setTextColor(38,51,47);doc.setFontSize(11);doc.text(SiddhaApp.getLanguage()==="te"?"రాశి చార్ట్ (D1)":"Rasi Chart (D1)",m,89);pdfChart(doc,c,m,95,110);
 doc.setFont("helvetica","bold");doc.text(SiddhaApp.getLanguage()==="te"?"ప్రస్తుత విమ్షోత్తరి దశ":"Current Vimshottari Dasha",m,217);doc.setFont("helvetica","normal");doc.setFontSize(9);doc.text((SiddhaApp.getLanguage()==="te"?"మహాదశ: ":"Mahadasha: ")+tr(data.dasha?.mahadasha?.lord||"—")+" • "+period(data.dasha?.mahadasha),m,225);doc.text((SiddhaApp.getLanguage()==="te"?"అంతర్దశ: ":"Antardasha: ")+tr(data.dasha?.antardasha?.lord||"—")+" • "+period(data.dasha?.antardasha),m,232);
 doc.setFont("helvetica","bold");doc.setFontSize(11);doc.text(SiddhaApp.getLanguage()==="te"?"గ్రహ స్థితులు":"Planetary Positions",m,244);let y=251;doc.setFontSize(7);doc.text(SiddhaApp.getLanguage()==="te"?"గ్రహం":"Planet",m,y);doc.text(SiddhaApp.getLanguage()==="te"?"రాశి":"Sign",42,y);doc.text(SiddhaApp.getLanguage()==="te"?"డిగ్రీ":"Degree",80,y);doc.text(SiddhaApp.getLanguage()==="te"?"భావం":"House",113,y);doc.text(SiddhaApp.getLanguage()==="te"?"నక్షత్రం":"Nakshatra",138,y);doc.setFont("helvetica","normal");y+=6;
 ps.forEach(p=>{doc.text(tr(p.name),m,y);doc.text(String(tr(p.sign)).slice(0,14),42,y);doc.text(deg(p.degree),80,y);doc.text(String(p.house),113,y);doc.text(String(trNak(p.nak)).slice(0,18),138,y);y+=6});
 doc.save("Siddha-Astro-Kundali-"+b.date+".pdf");
}
window.SiddhaKundali.downloadPdf=downloadPdf;